-- Dados na tabela ESTADO
insert into transporte.TB_ESTADO(NOME, SIGLA) values
	('Acre', 'AC'),
	('Amapá', 'AP'),
	('Amazonas', 'AM'),
	('Pará', 'PA'),
	('Rondônia', 'RO'),
	('Roraima', 'RR'),
	('Tocantins', 'TO'),
	('Alagoas', 'AL'),
	('Bahia', 'BA'),
	('Ceará', 'CE'),
	('Maranhão', 'MA'),
	('Paraíba', 'PB'),
	('Pernambuco', 'PE'),
	('Piauí', 'PI'),
	('Rio Grande do Norte', 'RN'),
	('Sergipe', 'SE'),
	('Espírito Santo', 'ES'),
	('Minas Gerais', 'MG'),
	('Rio de Janeiro', 'RJ'),
	('São Paulo', 'SP'),
	('Paraná', 'PR'),
	('Rio Grande do Sul', 'RS'),
	('Santa Catarina', 'SC'),
	('Distrito Federal', 'DF'),
	('Goiás', 'GO'),
	('Mato Grosso', 'MT'),
	('Mato Grosso do Sul', 'MS');


--Dados na tabela CIDADE
insert into transporte.TB_CIDADE(NOME, FK_ESTADO) values
	('Itapevi', 20),
	('Jandira', 20),
	('Barueri', 20),
	('Carapicuíba', 20),
	('Osasco', 20),
	('São Paulo', 20),
	('Caieiras', 20),
	('Franco da Rocha', 20),
	('Francisco Morato', 20),
	('Campo Limpo Paulista', 20),
	('Várzea Paulista', 20),
	('Jundiaí', 20),
	('Guarulhos', 20),
	('Itapevi', 20),
	('Itaquaquecetuba', 20),
	('Mogi das Cruzes', 20),
	('Suzano', 20),
	('São Caetano do Sul', 20),
	('Santo André', 20),
	('Mauá', 20),
	('Ribeirão Pires', 20),
	('Rio Grande da Serra', 20);